package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private Tuple t1;
    private Tuple t2;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        t1 = t2 = null;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        int i = getJoinPredicate().getField1();
        return child1.getTupleDesc().getFieldName(i);
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        int i = getJoinPredicate().getField2();
        return child2.getTupleDesc().getFieldName(i);
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        child1.open();
        child2.open();
        if(child1.hasNext() && child2.hasNext()) {
            t1 = child1.next();
            t2 = child2.next();
        }
        super.open();
    }

    public void close() {
        // some code goes here
        child1.close();
        child2.close();
        t1 = t2 = null;
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
        if(child1.hasNext() && child2.hasNext()) {
            t1 = child1.next();
            t2 = child2.next();
        }
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if(t1 == null) { return null; } //ei
        JoinPredicate p = getJoinPredicate();
        while(!p.filter(t1, t2)) {
            if(!child1.hasNext() && !child2.hasNext()) { return null; }
            advance();
        }

        //create and add new tuple
        TupleDesc td = getTupleDesc(),
                  td1 = t1.getTupleDesc();
        Tuple t = new Tuple(td);
        for(int i = 0; i < td.numFields(); i++) {
            if(i < td1.numFields()) {
                t.setField(i, t1.getField(i));
            } else {
                t.setField(i, t2.getField(i - td1.numFields()));
            }
        }
        advance();
        return t;
    }

    /**
     * Helper to take the next step in a nested loop join. Does nothing if
     * there are no tuples left.*/
    private void advance() throws TransactionAbortedException, DbException {
        if(!child1.hasNext() && !child2.hasNext()) { 
            t1 = t2 = null;
            return; 
        }
        if(!child2.hasNext()) {
            child2.rewind();
            t1 = child1.next();
        }
        t2 = child2.next();
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        DbIterator[] arr = new DbIterator[2];
        arr[0] = child1;
        arr[1] = child2;
        return arr;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        child1 = children[0];
        child2 = children[1];
    }

}
